"""Show recommended LLM model names for .env configuration."""

print("=" * 70)
print("RECOMMENDED LLM MODEL CONFIGURATION")
print("=" * 70)
print()
print("Add these to your .env file:")
print()
print("# Primary LLM (Google Gemini)")
print("LLM_MODEL_PRIMARY=gemini-2.5-flash-lite-preview-09-2025")
print()
print("# Fallback LLM (Groq)")
print("LLM_MODEL_FALLBACK=llama-3.1-8b-instant")
print()
print("=" * 70)
print()
print("Current issues detected:")
print("  ❌ Gemini model 'gemini-1.5-flash' is deprecated/not found")
print("  ❌ Groq model 'llama3-8b-8192' has been decommissioned")
print()
print("Alternatives:")
print("  - Gemini: gemini-2.0-flash-exp, gemini-1.5-pro, gemini-2.5-flash-lite")
print("  - Groq: llama-3.1-8b-instant, llama-3.1-70b-versatile, mixtral-8x7b-32768")
print()
print("=" * 70)
